---
title: React App Structure
---
flowchart TD
    A[index.js] --> B[App]
    B --> C[Other Components]
    B --> D[App.css]
    A --> E[index.css]
    B --> F[reportWebVitals.js]
    B --> G[setupTests.js] 